// <auto-generated />
using System;
using IchthusPOSWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IchthusPOSWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250327031108_DataSorting032720251111")]
    partial class DataSorting032720251111
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BatchDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasSerial")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfItems")
                        .HasColumnType("int");

                    b.Property<int>("PricelistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PricelistId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.CategoryFive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryFiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesFive");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.CategoryFour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryFourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesFour");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.CategoryThree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryThreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesThree");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.CategoryTwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryTwoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesTwo");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.CustomerTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTemps");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Pricelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Reseller")
                        .HasColumnType("int");

                    b.Property<int?>("VatEx")
                        .HasColumnType("int");

                    b.Property<int?>("VatInc")
                        .HasColumnType("int");

                    b.Property<int?>("ZeroRated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Pricelists");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryFiveId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryFourId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryThreeId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryTwoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSerial")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProductImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryFiveId");

                    b.HasIndex("CategoryFourId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryThreeId");

                    b.HasIndex("CategoryTwoId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.PurchasedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscountValue")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Subtotal")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("PurchasedProducts");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.SerialMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PricelistId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchasedProductId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SerialNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedProductId");

                    b.ToTable("SerialMains");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<string>("SerialName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("SerialNumbers");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.SerialTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PricelistId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SerialNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerialTemps");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Change")
                        .HasColumnType("int");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Payment")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreparedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int?>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Batch", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Pricelist", "Pricelist")
                        .WithMany("Batches")
                        .HasForeignKey("PricelistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pricelist");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Pricelist", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Color");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Product", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.CategoryFive", "CategoryFive")
                        .WithMany()
                        .HasForeignKey("CategoryFiveId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.CategoryFour", "CategoryFour")
                        .WithMany()
                        .HasForeignKey("CategoryFourId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.CategoryThree", "CategoryThree")
                        .WithMany()
                        .HasForeignKey("CategoryThreeId");

                    b.HasOne("IchthusPOSWeb.Models.Entities.CategoryTwo", "CategoryTwo")
                        .WithMany()
                        .HasForeignKey("CategoryTwoId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("CategoryFive");

                    b.Navigation("CategoryFour");

                    b.Navigation("CategoryThree");

                    b.Navigation("CategoryTwo");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.PurchasedProduct", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Transaction", null)
                        .WithMany("PurchasedProducts")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.SerialMain", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.PurchasedProduct", null)
                        .WithMany("SerialNumbers")
                        .HasForeignKey("PurchasedProductId");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.SerialNumber", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Batch", null)
                        .WithMany("SerialNumbers")
                        .HasForeignKey("BatchId");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Transaction", b =>
                {
                    b.HasOne("IchthusPOSWeb.Models.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Batch", b =>
                {
                    b.Navigation("SerialNumbers");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Pricelist", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.PurchasedProduct", b =>
                {
                    b.Navigation("SerialNumbers");
                });

            modelBuilder.Entity("IchthusPOSWeb.Models.Entities.Transaction", b =>
                {
                    b.Navigation("PurchasedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
